"""Add profile models

Revision ID: 40713eb3eb19
Revises: 20261002_000005
Create Date: 2026-10-04 19:35:01.066887
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '40713eb3eb19'
down_revision = '20261002_000005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dating_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('attraction_preference', sa.String(length=255), nullable=True),
    sa.Column('primary_intention', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('discovery_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('discovery_enabled', sa.Boolean(), nullable=False),
    sa.Column('target_audience', sa.String(length=255), nullable=True),
    sa.Column('travel_social_preference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('lifestyle_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('food_preferences', sa.String(length=255), nullable=True),
    sa.Column('smoking_preference', sa.String(length=100), nullable=True),
    sa.Column('alcohol_preference', sa.String(length=100), nullable=True),
    sa.Column('pets', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('profile_identities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('middle_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('pronouns', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('provider_identities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_subject', sa.String(length=255), nullable=False),
    sa.Column('provider_email', sa.String(length=255), nullable=True),
    sa.Column('provider_name', sa.String(length=255), nullable=True),
    sa.Column('provider_avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('last_synced_at', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_subject', name='uq_provider_identities_subject')
    )
    op.create_table('travel_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('travel_frequency', sa.String(length=100), nullable=True),
    sa.Column('preferred_trip_duration', sa.String(length=100), nullable=True),
    sa.Column('solo_group_preference', sa.String(length=100), nullable=True),
    sa.Column('travel_style', sa.Text(), nullable=True),
    sa.Column('compatibility_pace', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_table('spatial_ref_sys')
    op.drop_index('idx_destination_aliases_dest_id', table_name='destination_aliases')
    op.create_index(op.f('ix_destination_aliases_alias'), 'destination_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_destination_aliases_destination_id'), 'destination_aliases', ['destination_id'], unique=False)
    op.drop_index('idx_destinations_location_geom', table_name='destinations', postgresql_using='gist')
    op.drop_index('idx_destinations_slug', table_name='destinations')
    op.create_index(op.f('ix_destinations_country_code'), 'destinations', ['country_code'], unique=False)
    op.create_index(op.f('ix_destinations_slug'), 'destinations', ['slug'], unique=True)
    op.drop_index('idx_trip_intents_trip_id', table_name='trip_intents')
    op.create_index(op.f('ix_trip_intents_trip_id'), 'trip_intents', ['trip_id'], unique=False)
    op.drop_index('idx_trips_destination_id', table_name='trips')
    op.drop_index('idx_trips_user_id', table_name='trips')
    op.create_index(op.f('ix_trips_destination_id'), 'trips', ['destination_id'], unique=False)
    op.create_index(op.f('ix_trips_end_date'), 'trips', ['end_date'], unique=False)
    op.create_index(op.f('ix_trips_start_date'), 'trips', ['start_date'], unique=False)
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.drop_index('idx_user_locations_location_geom', table_name='user_locations', postgresql_using='gist')
    op.drop_index('idx_user_locations_user_id', table_name='user_locations')
    op.create_index(op.f('ix_user_locations_user_id'), 'user_locations', ['user_id'], unique=True)
    op.drop_index('ix_user_preference_options_user_category', table_name='user_preference_options')
    op.create_index('idx_user_reports_reported', 'user_reports', ['reported_id'], unique=False)
    op.create_index(op.f('ix_user_reports_reviewed_by_id'), 'user_reports', ['reviewed_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_reports_reviewed_by_id'), table_name='user_reports')
    op.drop_index('idx_user_reports_reported', table_name='user_reports')
    op.create_index('ix_user_preference_options_user_category', 'user_preference_options', ['user_id', 'category'], unique=False)
    op.drop_index(op.f('ix_user_locations_user_id'), table_name='user_locations')
    op.create_index('idx_user_locations_user_id', 'user_locations', ['user_id'], unique=False)
    op.create_index('idx_user_locations_location_geom', 'user_locations', ['location_geom'], unique=False, postgresql_using='gist')
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_start_date'), table_name='trips')
    op.drop_index(op.f('ix_trips_end_date'), table_name='trips')
    op.drop_index(op.f('ix_trips_destination_id'), table_name='trips')
    op.create_index('idx_trips_user_id', 'trips', ['user_id'], unique=False)
    op.create_index('idx_trips_destination_id', 'trips', ['destination_id'], unique=False)
    op.drop_index(op.f('ix_trip_intents_trip_id'), table_name='trip_intents')
    op.create_index('idx_trip_intents_trip_id', 'trip_intents', ['trip_id'], unique=False)
    op.drop_index(op.f('ix_destinations_slug'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_country_code'), table_name='destinations')
    op.create_index('idx_destinations_slug', 'destinations', ['slug'], unique=True)
    op.create_index('idx_destinations_location_geom', 'destinations', ['location_geom'], unique=False, postgresql_using='gist')
    op.drop_index(op.f('ix_destination_aliases_destination_id'), table_name='destination_aliases')
    op.drop_index(op.f('ix_destination_aliases_alias'), table_name='destination_aliases')
    op.create_index('idx_destination_aliases_dest_id', 'destination_aliases', ['destination_id'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('travel_preferences')
    op.drop_table('provider_identities')
    op.drop_table('profile_identities')
    op.drop_table('lifestyle_preferences')
    op.drop_table('discovery_preferences')
    op.drop_table('dating_preferences')
    # ### end Alembic commands ###
