"""
Synthetic presentation-dataset user definitions.

99 total: 34 female, 65 male.
All identities are clearly fictional demo accounts — NOT real people.
"""
from __future__ import annotations

from typing import TypedDict


class PersonSpec(TypedDict):
    seed_index: int          # 1–99
    gender: str              # "female" | "male"
    first_name: str
    last_name: str
    date_of_birth: str       # YYYY-MM-DD (all 18+)
    bio: str
    city: str
    region: str
    country_code: str        # ISO 3166-1 alpha-2
    approx_lat: float
    approx_lon: float
    languages: list[str]     # values for category=language
    travel_intentions: list[str]   # values for category=travel_intention
    dating_intentions: list[str]   # values for category=dating_intention
    dating_preferences: list[str]  # values for category=dating_preference
    discovery_preferences: list[str]  # values for category=discovery_preference
    interest_codes: list[str]      # codes from interests catalog
    trip_destination_slugs: list[str]  # 1–3 destinations per user
    companion_preference: str      # travelling_alone | open_to_companion | travelling_with_group
    trip_visibility: str           # discoverable | public | private


# ---------------------------------------------------------------------------
# Canonical interest codes available in the DB
# ---------------------------------------------------------------------------
ALL_INTERESTS = [
    "food_walks", "hiking", "photography", "heritage",
    "art_design", "live_music", "beaches", "local_culture",
]

# ---------------------------------------------------------------------------
# 34 Female profiles (seed_index 1–34)
# ---------------------------------------------------------------------------
FEMALE_PROFILES: list[PersonSpec] = [
    {
        "seed_index": 1, "gender": "female",
        "first_name": "Aanya", "last_name": "Sharma",
        "date_of_birth": "1997-03-12",
        "bio": "Solo traveller and street-food addict. Chasing sunsets in every time zone. Certified yoga instructor by day, live-music enthusiast by night.",
        "city": "Mumbai", "region": "Maharashtra", "country_code": "IN",
        "approx_lat": 19.07, "approx_lon": 72.87,
        "languages": ["Hindi", "English"],
        "travel_intentions": ["travel_companion", "friends_social"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["men"],
        "discovery_preferences": ["men", "everyone"],
        "interest_codes": ["food_walks", "live_music", "photography"],
        "trip_destination_slugs": ["goa", "bali"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 2, "gender": "female",
        "first_name": "Priya", "last_name": "Nair",
        "date_of_birth": "1994-07-22",
        "bio": "Kerala-born wanderer. I find magic in heritage temples, quiet hill stations, and unexpected chai conversations.",
        "city": "Kochi", "region": "Kerala", "country_code": "IN",
        "approx_lat": 9.93, "approx_lon": 76.26,
        "languages": ["Malayalam", "English", "Hindi"],
        "travel_intentions": ["travel_companion", "activity_partner"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["men"],
        "discovery_preferences": ["men"],
        "interest_codes": ["heritage", "local_culture", "hiking"],
        "trip_destination_slugs": ["kochi", "kashmir"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 3, "gender": "female",
        "first_name": "Meera", "last_name": "Krishnan",
        "date_of_birth": "2000-01-05",
        "bio": "Architecture grad who photographs every doorway. Currently obsessed with old Chettinad mansions and crumbling forts.",
        "city": "Chennai", "region": "Tamil Nadu", "country_code": "IN",
        "approx_lat": 13.08, "approx_lon": 80.27,
        "languages": ["Tamil", "English"],
        "travel_intentions": ["friends_social", "activity_partner"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["everyone"],
        "discovery_preferences": ["everyone"],
        "interest_codes": ["heritage", "photography", "art_design"],
        "trip_destination_slugs": ["chennai", "hyderabad"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 4, "gender": "female",
        "first_name": "Sonia", "last_name": "Batra",
        "date_of_birth": "1991-11-18",
        "bio": "Finance analyst who escapes spreadsheets through trekking. Manali is my happy place. Always planning the next Himalayan adventure.",
        "city": "New Delhi", "region": "Delhi", "country_code": "IN",
        "approx_lat": 28.61, "approx_lon": 77.20,
        "languages": ["Hindi", "English", "Punjabi"],
        "travel_intentions": ["travel_companion", "activity_partner"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["men"],
        "discovery_preferences": ["men"],
        "interest_codes": ["hiking", "photography", "local_culture"],
        "trip_destination_slugs": ["manali", "kashmir"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 5, "gender": "female",
        "first_name": "Divya", "last_name": "Rao",
        "date_of_birth": "1999-09-09",
        "bio": "Wildlife photographer & conservationist. I've been on 23 safaris and counting. Ask me about the best national parks in South India.",
        "city": "Bengaluru", "region": "Karnataka", "country_code": "IN",
        "approx_lat": 12.97, "approx_lon": 77.59,
        "languages": ["Kannada", "English", "Hindi"],
        "travel_intentions": ["activity_partner", "friends_social"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["everyone"],
        "discovery_preferences": ["everyone"],
        "interest_codes": ["photography", "hiking", "local_culture"],
        "trip_destination_slugs": ["goa", "bali"],
        "companion_preference": "travelling_alone",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 6, "gender": "female",
        "first_name": "Riya", "last_name": "Desai",
        "date_of_birth": "1996-04-30",
        "bio": "Pastry chef and travel blogger. I document local desserts everywhere I go. Currently planning a sweets tour of Rajasthan.",
        "city": "Ahmedabad", "region": "Gujarat", "country_code": "IN",
        "approx_lat": 23.02, "approx_lon": 72.57,
        "languages": ["Gujarati", "Hindi", "English"],
        "travel_intentions": ["travel_companion", "local_guide"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["men"],
        "discovery_preferences": ["men", "everyone"],
        "interest_codes": ["food_walks", "local_culture", "heritage"],
        "trip_destination_slugs": ["jaipur", "udaipur"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 7, "gender": "female",
        "first_name": "Kavya", "last_name": "Menon",
        "date_of_birth": "1993-12-03",
        "bio": "Marine biologist turned travel guide. Coral reefs and coconut shores are my natural habitat. Andamans next!",
        "city": "Thiruvananthapuram", "region": "Kerala", "country_code": "IN",
        "approx_lat": 8.52, "approx_lon": 76.93,
        "languages": ["Malayalam", "English"],
        "travel_intentions": ["activity_partner", "travel_companion"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["beaches", "hiking", "photography"],
        "trip_destination_slugs": ["kochi", "bali"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 8, "gender": "female",
        "first_name": "Ananya", "last_name": "Ghosh",
        "date_of_birth": "1998-06-14",
        "bio": "Kolkata girl with a passion for art galleries and ghats. I sketch every city I visit. Coffee is my travel fuel.",
        "city": "Kolkata", "region": "West Bengal", "country_code": "IN",
        "approx_lat": 22.57, "approx_lon": 88.36,
        "languages": ["Bengali", "English", "Hindi"],
        "travel_intentions": ["friends_social", "activity_partner"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["everyone"],
        "discovery_preferences": ["everyone"],
        "interest_codes": ["art_design", "heritage", "local_culture"],
        "trip_destination_slugs": ["kolkata", "varanasi"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 9, "gender": "female",
        "first_name": "Ishita", "last_name": "Verma",
        "date_of_birth": "2001-02-19",
        "bio": "Student journalist and backpacker. I find the best stories on overnight trains. Budget travel is an art form.",
        "city": "Lucknow", "region": "Uttar Pradesh", "country_code": "IN",
        "approx_lat": 26.85, "approx_lon": 80.95,
        "languages": ["Hindi", "English", "Urdu"],
        "travel_intentions": ["friends_social", "travel_companion"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["men"],
        "discovery_preferences": ["men"],
        "interest_codes": ["heritage", "food_walks", "local_culture"],
        "trip_destination_slugs": ["varanasi", "new-delhi"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 10, "gender": "female",
        "first_name": "Tanvi", "last_name": "Joshi",
        "date_of_birth": "1995-08-07",
        "bio": "Classical dancer and cultural explorer. Dance festivals around the world are my itinerary. Khajuraho to Edinburgh.",
        "city": "Pune", "region": "Maharashtra", "country_code": "IN",
        "approx_lat": 18.52, "approx_lon": 73.86,
        "languages": ["Marathi", "Hindi", "English"],
        "travel_intentions": ["activity_partner", "travel_companion"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["men"],
        "discovery_preferences": ["men"],
        "interest_codes": ["art_design", "live_music", "heritage"],
        "trip_destination_slugs": ["paris", "goa"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 11, "gender": "female",
        "first_name": "Nidhi", "last_name": "Aggarwal",
        "date_of_birth": "1992-05-27",
        "bio": "Entrepreneur and slow traveller. I spend at least a month in every city. Working from cafes is my superpower.",
        "city": "Jaipur", "region": "Rajasthan", "country_code": "IN",
        "approx_lat": 26.91, "approx_lon": 75.79,
        "languages": ["Hindi", "English", "Rajasthani"],
        "travel_intentions": ["travel_companion", "friends_social"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["men"],
        "discovery_preferences": ["men", "everyone"],
        "interest_codes": ["local_culture", "heritage", "food_walks"],
        "trip_destination_slugs": ["jaipur", "singapore"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 12, "gender": "female",
        "first_name": "Pooja", "last_name": "Pillai",
        "date_of_birth": "1990-10-15",
        "bio": "Ayurveda practitioner and mindful traveller. I seek wellness retreats, ancient healing, and quiet temples across Asia.",
        "city": "Palakkad", "region": "Kerala", "country_code": "IN",
        "approx_lat": 10.78, "approx_lon": 76.65,
        "languages": ["Malayalam", "English", "Sanskrit"],
        "travel_intentions": ["travel_companion", "activity_partner"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["men"],
        "discovery_preferences": ["men"],
        "interest_codes": ["heritage", "local_culture", "hiking"],
        "trip_destination_slugs": ["rishikesh", "bali"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 13, "gender": "female",
        "first_name": "Shreya", "last_name": "Chattopadhyay",
        "date_of_birth": "1997-07-04",
        "bio": "Bengali bookworm and monsoon lover. I read a novel set in every city I visit. Tagore's Shantiniketan is my spiritual home.",
        "city": "Kolkata", "region": "West Bengal", "country_code": "IN",
        "approx_lat": 22.57, "approx_lon": 88.37,
        "languages": ["Bengali", "English", "Hindi"],
        "travel_intentions": ["friends_social", "activity_partner"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["men"],
        "discovery_preferences": ["men"],
        "interest_codes": ["art_design", "local_culture", "photography"],
        "trip_destination_slugs": ["kolkata", "london"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 14, "gender": "female",
        "first_name": "Aditi", "last_name": "Kulkarni",
        "date_of_birth": "1989-03-21",
        "bio": "Architect turned digital nomad. I design buildings but prefer sleeping in tents. Mountains > meetings.",
        "city": "Bengaluru", "region": "Karnataka", "country_code": "IN",
        "approx_lat": 12.96, "approx_lon": 77.60,
        "languages": ["Kannada", "English", "Hindi"],
        "travel_intentions": ["travel_companion", "activity_partner"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["everyone"],
        "discovery_preferences": ["everyone"],
        "interest_codes": ["hiking", "photography", "art_design"],
        "trip_destination_slugs": ["manali", "kashmir"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 15, "gender": "female",
        "first_name": "Sneha", "last_name": "Pandey",
        "date_of_birth": "2002-09-10",
        "bio": "Dance choreographer and street art enthusiast. I document murals from Mumbai to Melbourne.",
        "city": "Mumbai", "region": "Maharashtra", "country_code": "IN",
        "approx_lat": 19.08, "approx_lon": 72.88,
        "languages": ["Hindi", "English", "Marathi"],
        "travel_intentions": ["activity_partner", "friends_social"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["everyone"],
        "discovery_preferences": ["everyone"],
        "interest_codes": ["art_design", "live_music", "local_culture"],
        "trip_destination_slugs": ["goa", "mumbai"],
        "companion_preference": "travelling_with_group",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 16, "gender": "female",
        "first_name": "Radha", "last_name": "Iyer",
        "date_of_birth": "1996-02-28",
        "bio": "Carnatic vocalist on a world music discovery tour. I believe every culture has a song that connects us.",
        "city": "Chennai", "region": "Tamil Nadu", "country_code": "IN",
        "approx_lat": 13.07, "approx_lon": 80.26,
        "languages": ["Tamil", "English", "Telugu"],
        "travel_intentions": ["activity_partner", "friends_social"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["men"],
        "discovery_preferences": ["men"],
        "interest_codes": ["live_music", "heritage", "local_culture"],
        "trip_destination_slugs": ["varanasi", "london"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 17, "gender": "female",
        "first_name": "Tara", "last_name": "Singh",
        "date_of_birth": "1994-11-11",
        "bio": "Mountaineer & wilderness guide from Chandigarh. Conquered three 6000m+ peaks. Next goal: Stok Kangri.",
        "city": "Chandigarh", "region": "Punjab", "country_code": "IN",
        "approx_lat": 30.73, "approx_lon": 76.77,
        "languages": ["Punjabi", "Hindi", "English"],
        "travel_intentions": ["activity_partner", "travel_companion"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["men"],
        "discovery_preferences": ["men", "everyone"],
        "interest_codes": ["hiking", "photography", "local_culture"],
        "trip_destination_slugs": ["kashmir", "manali"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 18, "gender": "female",
        "first_name": "Fiona", "last_name": "D'Souza",
        "date_of_birth": "1993-08-16",
        "bio": "Goan-born marine painter. I paint the sea at every port. Half my luggage is art supplies.",
        "city": "Panaji", "region": "Goa", "country_code": "IN",
        "approx_lat": 15.50, "approx_lon": 73.83,
        "languages": ["Konkani", "English", "Portuguese"],
        "travel_intentions": ["activity_partner", "friends_social"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["men"],
        "discovery_preferences": ["men"],
        "interest_codes": ["art_design", "beaches", "photography"],
        "trip_destination_slugs": ["goa", "singapore"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 19, "gender": "female",
        "first_name": "Nalini", "last_name": "Reddy",
        "date_of_birth": "1991-04-05",
        "bio": "Data scientist who unwinds by visiting ancient temples. Hyderabad's Charminar to Angkor Wat — history is my data.",
        "city": "Hyderabad", "region": "Telangana", "country_code": "IN",
        "approx_lat": 17.38, "approx_lon": 78.49,
        "languages": ["Telugu", "Hindi", "English"],
        "travel_intentions": ["travel_companion", "activity_partner"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["men"],
        "discovery_preferences": ["men"],
        "interest_codes": ["heritage", "local_culture", "food_walks"],
        "trip_destination_slugs": ["hyderabad", "bangkok"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 20, "gender": "female",
        "first_name": "Layla", "last_name": "Fernandez",
        "date_of_birth": "2000-06-20",
        "bio": "Half-Goan, half-Mangalorean. I cook fusion food and travel for recipes. My Instagram is a recipe trail.",
        "city": "Mangaluru", "region": "Karnataka", "country_code": "IN",
        "approx_lat": 12.91, "approx_lon": 74.86,
        "languages": ["Konkani", "Tulu", "English"],
        "travel_intentions": ["friends_social", "local_guide"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["men"],
        "discovery_preferences": ["men", "everyone"],
        "interest_codes": ["food_walks", "beaches", "local_culture"],
        "trip_destination_slugs": ["goa", "bali"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 21, "gender": "female",
        "first_name": "Harsha", "last_name": "Banerjee",
        "date_of_birth": "1988-12-25",
        "bio": "HR director who travels solo to recharge. I read poetry in train compartments. Varanasi changed my life.",
        "city": "Kolkata", "region": "West Bengal", "country_code": "IN",
        "approx_lat": 22.56, "approx_lon": 88.35,
        "languages": ["Bengali", "Hindi", "English"],
        "travel_intentions": ["travel_companion", "friends_social"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["men"],
        "discovery_preferences": ["men"],
        "interest_codes": ["heritage", "local_culture", "art_design"],
        "trip_destination_slugs": ["varanasi", "kolkata"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 22, "gender": "female",
        "first_name": "Simran", "last_name": "Kaur",
        "date_of_birth": "1999-03-17",
        "bio": "Fashion designer from Delhi. I source vintage fabrics worldwide. Tokyo thrift stores are heaven.",
        "city": "New Delhi", "region": "Delhi", "country_code": "IN",
        "approx_lat": 28.63, "approx_lon": 77.22,
        "languages": ["Punjabi", "Hindi", "English"],
        "travel_intentions": ["activity_partner", "friends_social"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["everyone"],
        "discovery_preferences": ["everyone"],
        "interest_codes": ["art_design", "local_culture", "photography"],
        "trip_destination_slugs": ["tokyo", "singapore"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 23, "gender": "female",
        "first_name": "Preethi", "last_name": "Subramanian",
        "date_of_birth": "1997-10-31",
        "bio": "IIT grad turned travel tech founder. I build apps for travellers. When not coding, I'm in a new country.",
        "city": "Chennai", "region": "Tamil Nadu", "country_code": "IN",
        "approx_lat": 13.09, "approx_lon": 80.28,
        "languages": ["Tamil", "English"],
        "travel_intentions": ["travel_companion", "activity_partner"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["men"],
        "discovery_preferences": ["men"],
        "interest_codes": ["local_culture", "food_walks", "photography"],
        "trip_destination_slugs": ["singapore", "london"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 24, "gender": "female",
        "first_name": "Geeta", "last_name": "Saxena",
        "date_of_birth": "1985-01-14",
        "bio": "Retired army officer's daughter, now a teacher and solo trekker. I've traversed Spiti three times.",
        "city": "Shimla", "region": "Himachal Pradesh", "country_code": "IN",
        "approx_lat": 31.10, "approx_lon": 77.17,
        "languages": ["Hindi", "English", "Pahari"],
        "travel_intentions": ["activity_partner", "travel_companion"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["men"],
        "discovery_preferences": ["men"],
        "interest_codes": ["hiking", "local_culture", "photography"],
        "trip_destination_slugs": ["manali", "rishikesh"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 25, "gender": "female",
        "first_name": "Zara", "last_name": "Khan",
        "date_of_birth": "2001-05-05",
        "bio": "Musician and beach lover from Bhopal. I play the sitar under open skies. Goa festivals are my calendar.",
        "city": "Bhopal", "region": "Madhya Pradesh", "country_code": "IN",
        "approx_lat": 23.26, "approx_lon": 77.41,
        "languages": ["Hindi", "English", "Urdu"],
        "travel_intentions": ["friends_social", "activity_partner"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["men"],
        "discovery_preferences": ["men", "everyone"],
        "interest_codes": ["live_music", "beaches", "local_culture"],
        "trip_destination_slugs": ["goa", "bali"],
        "companion_preference": "travelling_with_group",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 26, "gender": "female",
        "first_name": "Amrita", "last_name": "Devi",
        "date_of_birth": "1990-08-02",
        "bio": "Yoga teacher and Ayurveda cook from Rishikesh. I lead wellness retreats across India and Bali.",
        "city": "Rishikesh", "region": "Uttarakhand", "country_code": "IN",
        "approx_lat": 30.09, "approx_lon": 78.27,
        "languages": ["Hindi", "English", "Sanskrit"],
        "travel_intentions": ["travel_companion", "local_guide"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["men"],
        "discovery_preferences": ["men"],
        "interest_codes": ["hiking", "local_culture", "heritage"],
        "trip_destination_slugs": ["rishikesh", "bali"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 27, "gender": "female",
        "first_name": "Kritika", "last_name": "Tiwari",
        "date_of_birth": "1998-02-14",
        "bio": "Food critic and culinary traveller. My rule: eat at least one meal per city that I can't pronounce.",
        "city": "Varanasi", "region": "Uttar Pradesh", "country_code": "IN",
        "approx_lat": 25.32, "approx_lon": 83.01,
        "languages": ["Hindi", "English", "Bhojpuri"],
        "travel_intentions": ["local_guide", "activity_partner"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["everyone"],
        "discovery_preferences": ["everyone"],
        "interest_codes": ["food_walks", "heritage", "local_culture"],
        "trip_destination_slugs": ["varanasi", "kolkata"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 28, "gender": "female",
        "first_name": "Manya", "last_name": "Oberoi",
        "date_of_birth": "1995-06-08",
        "bio": "Former flight attendant turned travel writer. 48 countries and still collecting passport stamps.",
        "city": "Mumbai", "region": "Maharashtra", "country_code": "IN",
        "approx_lat": 19.06, "approx_lon": 72.86,
        "languages": ["Hindi", "English", "French"],
        "travel_intentions": ["travel_companion", "friends_social"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["men"],
        "discovery_preferences": ["men"],
        "interest_codes": ["local_culture", "food_walks", "photography"],
        "trip_destination_slugs": ["paris", "dubai"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 29, "gender": "female",
        "first_name": "Bhavna", "last_name": "Mehta",
        "date_of_birth": "2003-04-22",
        "bio": "Art history student who wants to see every Van Gogh in person. European museums are on my bucket list.",
        "city": "Surat", "region": "Gujarat", "country_code": "IN",
        "approx_lat": 21.17, "approx_lon": 72.83,
        "languages": ["Gujarati", "Hindi", "English"],
        "travel_intentions": ["activity_partner", "travel_companion"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["everyone"],
        "discovery_preferences": ["everyone"],
        "interest_codes": ["art_design", "heritage", "photography"],
        "trip_destination_slugs": ["paris", "london"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 30, "gender": "female",
        "first_name": "Vandana", "last_name": "Chaudhary",
        "date_of_birth": "1987-09-29",
        "bio": "Senior nurse and solo explorer. I believe travel is the best therapy. 15 countries, zero complaints.",
        "city": "Jaipur", "region": "Rajasthan", "country_code": "IN",
        "approx_lat": 26.92, "approx_lon": 75.80,
        "languages": ["Hindi", "English", "Rajasthani"],
        "travel_intentions": ["travel_companion", "friends_social"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["men"],
        "discovery_preferences": ["men"],
        "interest_codes": ["heritage", "local_culture", "food_walks"],
        "trip_destination_slugs": ["jaipur", "dubai"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 31, "gender": "female",
        "first_name": "Ria", "last_name": "Parekh",
        "date_of_birth": "2000-11-30",
        "bio": "Textile designer on a perpetual colour hunt. I've explored craft clusters from Kutch to Oaxaca.",
        "city": "Ahmedabad", "region": "Gujarat", "country_code": "IN",
        "approx_lat": 23.03, "approx_lon": 72.58,
        "languages": ["Gujarati", "Hindi", "English"],
        "travel_intentions": ["activity_partner", "friends_social"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["everyone"],
        "discovery_preferences": ["everyone"],
        "interest_codes": ["art_design", "local_culture", "heritage"],
        "trip_destination_slugs": ["jaipur", "udaipur"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 32, "gender": "female",
        "first_name": "Sunita", "last_name": "Patil",
        "date_of_birth": "1986-07-17",
        "bio": "School principal and weekend biker. I lead all-women motorcycle trips across the Deccan plateau.",
        "city": "Kolhapur", "region": "Maharashtra", "country_code": "IN",
        "approx_lat": 16.70, "approx_lon": 74.24,
        "languages": ["Marathi", "Hindi", "English"],
        "travel_intentions": ["activity_partner", "travel_companion"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["men"],
        "discovery_preferences": ["men", "everyone"],
        "interest_codes": ["hiking", "local_culture", "photography"],
        "trip_destination_slugs": ["goa", "kochi"],
        "companion_preference": "travelling_with_group",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 33, "gender": "female",
        "first_name": "Chitra", "last_name": "Narayanan",
        "date_of_birth": "1994-01-09",
        "bio": "Environmental scientist studying coastal ecosystems. Beach cleanups + sunrises are my weekend rituals.",
        "city": "Pondicherry", "region": "Puducherry", "country_code": "IN",
        "approx_lat": 11.93, "approx_lon": 79.83,
        "languages": ["Tamil", "French", "English"],
        "travel_intentions": ["activity_partner", "local_guide"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["men"],
        "discovery_preferences": ["men"],
        "interest_codes": ["beaches", "local_culture", "photography"],
        "trip_destination_slugs": ["kochi", "bali"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 34, "gender": "female",
        "first_name": "Ankita", "last_name": "Rawat",
        "date_of_birth": "1996-03-03",
        "bio": "Glaciologist and trek guide from Uttarakhand. I know the mountains better than city maps.",
        "city": "Dehradun", "region": "Uttarakhand", "country_code": "IN",
        "approx_lat": 30.32, "approx_lon": 78.03,
        "languages": ["Garhwali", "Hindi", "English"],
        "travel_intentions": ["activity_partner", "travel_companion"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["men"],
        "discovery_preferences": ["men"],
        "interest_codes": ["hiking", "photography", "local_culture"],
        "trip_destination_slugs": ["rishikesh", "kashmir"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
]

# ---------------------------------------------------------------------------
# 65 Male profiles (seed_index 35–99)
# ---------------------------------------------------------------------------
MALE_PROFILES: list[PersonSpec] = [
    {
        "seed_index": 35, "gender": "male",
        "first_name": "Arjun", "last_name": "Kapoor",
        "date_of_birth": "1996-05-15",
        "bio": "Cinematographer and road-tripper. I've driven the Leh-Manali highway six times. Every frame is a story.",
        "city": "Mumbai", "region": "Maharashtra", "country_code": "IN",
        "approx_lat": 19.07, "approx_lon": 72.87,
        "languages": ["Hindi", "English"],
        "travel_intentions": ["travel_companion", "activity_partner"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["photography", "hiking", "local_culture"],
        "trip_destination_slugs": ["manali", "kashmir"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 36, "gender": "male",
        "first_name": "Rohit", "last_name": "Malhotra",
        "date_of_birth": "1993-09-20",
        "bio": "Startup founder on a sabbatical. Currently slow-travelling South-East Asia. Working from beach cafes.",
        "city": "Bengaluru", "region": "Karnataka", "country_code": "IN",
        "approx_lat": 12.97, "approx_lon": 77.59,
        "languages": ["Hindi", "English", "Kannada"],
        "travel_intentions": ["travel_companion", "friends_social"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["local_culture", "food_walks", "live_music"],
        "trip_destination_slugs": ["bali", "singapore"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 37, "gender": "male",
        "first_name": "Vikram", "last_name": "Nambiar",
        "date_of_birth": "1991-02-08",
        "bio": "Kerala chef exploring Asian cuisines. Every city is a tasting menu. My spice rack has 40 countries represented.",
        "city": "Kochi", "region": "Kerala", "country_code": "IN",
        "approx_lat": 9.93, "approx_lon": 76.26,
        "languages": ["Malayalam", "English", "Hindi"],
        "travel_intentions": ["local_guide", "activity_partner"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women", "everyone"],
        "interest_codes": ["food_walks", "local_culture", "heritage"],
        "trip_destination_slugs": ["kochi", "bangkok"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 38, "gender": "male",
        "first_name": "Karan", "last_name": "Mehra",
        "date_of_birth": "1998-11-03",
        "bio": "Environmental lawyer and weekend trekker. I argue for forests in court and sleep under stars on weekends.",
        "city": "New Delhi", "region": "Delhi", "country_code": "IN",
        "approx_lat": 28.61, "approx_lon": 77.21,
        "languages": ["Hindi", "English", "Punjabi"],
        "travel_intentions": ["activity_partner", "travel_companion"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["hiking", "photography", "heritage"],
        "trip_destination_slugs": ["rishikesh", "kashmir"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 39, "gender": "male",
        "first_name": "Aditya", "last_name": "Srinivasan",
        "date_of_birth": "1994-04-14",
        "bio": "IIM alum and travel blogger. I write about budget luxury — good experiences at honest prices.",
        "city": "Chennai", "region": "Tamil Nadu", "country_code": "IN",
        "approx_lat": 13.08, "approx_lon": 80.27,
        "languages": ["Tamil", "English", "Hindi"],
        "travel_intentions": ["travel_companion", "friends_social"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["local_culture", "food_walks", "photography"],
        "trip_destination_slugs": ["singapore", "dubai"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 40, "gender": "male",
        "first_name": "Nikhil", "last_name": "Gupta",
        "date_of_birth": "1990-07-07",
        "bio": "Chartered accountant by profession, mountaineer by passion. Numbers by day, peaks by weekend.",
        "city": "Lucknow", "region": "Uttar Pradesh", "country_code": "IN",
        "approx_lat": 26.85, "approx_lon": 80.95,
        "languages": ["Hindi", "English", "Urdu"],
        "travel_intentions": ["activity_partner", "travel_companion"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["hiking", "photography", "local_culture"],
        "trip_destination_slugs": ["manali", "rishikesh"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 41, "gender": "male",
        "first_name": "Sameer", "last_name": "Joshi",
        "date_of_birth": "2000-10-25",
        "bio": "Music producer who records ambient soundscapes of cities. Bangalore jazz bars to Goa trance — I capture it all.",
        "city": "Bengaluru", "region": "Karnataka", "country_code": "IN",
        "approx_lat": 12.97, "approx_lon": 77.60,
        "languages": ["Kannada", "English", "Hindi"],
        "travel_intentions": ["friends_social", "activity_partner"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["everyone"],
        "discovery_preferences": ["everyone"],
        "interest_codes": ["live_music", "local_culture", "art_design"],
        "trip_destination_slugs": ["goa", "tokyo"],
        "companion_preference": "travelling_with_group",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 42, "gender": "male",
        "first_name": "Dev", "last_name": "Chatterjee",
        "date_of_birth": "1987-12-01",
        "bio": "Photojournalist for a national news agency. I've covered 14 countries, from floods to festivals.",
        "city": "Kolkata", "region": "West Bengal", "country_code": "IN",
        "approx_lat": 22.57, "approx_lon": 88.36,
        "languages": ["Bengali", "Hindi", "English"],
        "travel_intentions": ["travel_companion", "activity_partner"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["photography", "heritage", "local_culture"],
        "trip_destination_slugs": ["kolkata", "london"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 43, "gender": "male",
        "first_name": "Harsh", "last_name": "Agarwal",
        "date_of_birth": "2002-03-28",
        "bio": "Gap-year traveller post-engineering. I want to visit 30 countries before I turn 25. Currently at 12.",
        "city": "Jaipur", "region": "Rajasthan", "country_code": "IN",
        "approx_lat": 26.91, "approx_lon": 75.78,
        "languages": ["Hindi", "English", "Rajasthani"],
        "travel_intentions": ["travel_companion", "friends_social"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women", "everyone"],
        "interest_codes": ["heritage", "local_culture", "food_walks"],
        "trip_destination_slugs": ["jaipur", "paris"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 44, "gender": "male",
        "first_name": "Tarun", "last_name": "Bhatt",
        "date_of_birth": "1996-01-22",
        "bio": "Wildlife biologist tagging leopards by day, trail running by evening. The jungle is my office.",
        "city": "Raipur", "region": "Chhattisgarh", "country_code": "IN",
        "approx_lat": 21.25, "approx_lon": 81.63,
        "languages": ["Hindi", "English", "Chhattisgarhi"],
        "travel_intentions": ["activity_partner", "travel_companion"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["hiking", "photography", "local_culture"],
        "trip_destination_slugs": ["kochi", "manali"],
        "companion_preference": "travelling_alone",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 45, "gender": "male",
        "first_name": "Manish", "last_name": "Tripathi",
        "date_of_birth": "1992-06-18",
        "bio": "Historian and heritage walk curator in Varanasi. I translate ancient ghats for the modern traveller.",
        "city": "Varanasi", "region": "Uttar Pradesh", "country_code": "IN",
        "approx_lat": 25.32, "approx_lon": 83.01,
        "languages": ["Hindi", "English", "Sanskrit", "Bhojpuri"],
        "travel_intentions": ["local_guide", "friends_social"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["heritage", "local_culture", "photography"],
        "trip_destination_slugs": ["varanasi", "jaipur"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 46, "gender": "male",
        "first_name": "Akash", "last_name": "Pillai",
        "date_of_birth": "1999-08-12",
        "bio": "Coastal engineer and scuba instructor. The ocean is home. I've dived from the Andamans to the Maldives.",
        "city": "Thiruvananthapuram", "region": "Kerala", "country_code": "IN",
        "approx_lat": 8.51, "approx_lon": 76.94,
        "languages": ["Malayalam", "English", "Tamil"],
        "travel_intentions": ["activity_partner", "travel_companion"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["beaches", "hiking", "photography"],
        "trip_destination_slugs": ["kochi", "bali"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 47, "gender": "male",
        "first_name": "Gaurav", "last_name": "Yadav",
        "date_of_birth": "1995-04-04",
        "bio": "Agricultural scientist fascinated by rural food systems. Every village has a recipe the world hasn't tasted.",
        "city": "Nagpur", "region": "Maharashtra", "country_code": "IN",
        "approx_lat": 21.15, "approx_lon": 79.09,
        "languages": ["Hindi", "Marathi", "English"],
        "travel_intentions": ["local_guide", "activity_partner"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["food_walks", "local_culture", "heritage"],
        "trip_destination_slugs": ["hyderabad", "mumbai"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 48, "gender": "male",
        "first_name": "Suresh", "last_name": "Rajan",
        "date_of_birth": "1984-11-27",
        "bio": "Ex-Navy officer and sailing enthusiast. I've circumnavigated India by sea. Next: Indian Ocean crossing.",
        "city": "Mumbai", "region": "Maharashtra", "country_code": "IN",
        "approx_lat": 19.05, "approx_lon": 72.84,
        "languages": ["Tamil", "Hindi", "English"],
        "travel_intentions": ["activity_partner", "travel_companion"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["beaches", "local_culture", "photography"],
        "trip_destination_slugs": ["goa", "dubai"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 49, "gender": "male",
        "first_name": "Prashant", "last_name": "Hegde",
        "date_of_birth": "1997-07-19",
        "bio": "Stand-up comedian on tour. Every city gives me new material. Mumbai nights, Bengaluru wit, Goa energy.",
        "city": "Bengaluru", "region": "Karnataka", "country_code": "IN",
        "approx_lat": 12.98, "approx_lon": 77.61,
        "languages": ["Kannada", "Hindi", "English"],
        "travel_intentions": ["friends_social", "activity_partner"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women", "everyone"],
        "interest_codes": ["live_music", "food_walks", "local_culture"],
        "trip_destination_slugs": ["mumbai", "goa"],
        "companion_preference": "travelling_with_group",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 50, "gender": "male",
        "first_name": "Rajan", "last_name": "Kumar",
        "date_of_birth": "1989-02-02",
        "bio": "Rural development officer who hikes on leave. The Himalayas reboot me every year.",
        "city": "Patna", "region": "Bihar", "country_code": "IN",
        "approx_lat": 25.59, "approx_lon": 85.13,
        "languages": ["Maithili", "Hindi", "English"],
        "travel_intentions": ["travel_companion", "friends_social"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["heritage", "hiking", "local_culture"],
        "trip_destination_slugs": ["varanasi", "rishikesh"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 51, "gender": "male",
        "first_name": "Anand", "last_name": "Krishnaswamy",
        "date_of_birth": "1993-05-10",
        "bio": "Classical violinist who busks in train stations across Europe and Asia. Music is the universal passport.",
        "city": "Chennai", "region": "Tamil Nadu", "country_code": "IN",
        "approx_lat": 13.07, "approx_lon": 80.26,
        "languages": ["Tamil", "English", "French"],
        "travel_intentions": ["activity_partner", "friends_social"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["live_music", "art_design", "local_culture"],
        "trip_destination_slugs": ["paris", "london"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 52, "gender": "male",
        "first_name": "Kabir", "last_name": "Chauhan",
        "date_of_birth": "1998-09-30",
        "bio": "Documentary filmmaker covering India's vanishing crafts. I carry a 4K camera and a moral compass.",
        "city": "Ahmedabad", "region": "Gujarat", "country_code": "IN",
        "approx_lat": 23.02, "approx_lon": 72.57,
        "languages": ["Gujarati", "Hindi", "English"],
        "travel_intentions": ["activity_partner", "local_guide"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["art_design", "heritage", "photography"],
        "trip_destination_slugs": ["jaipur", "udaipur"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 53, "gender": "male",
        "first_name": "Pradeep", "last_name": "Balaji",
        "date_of_birth": "1986-03-06",
        "bio": "Cardiologist who treks for heart health. Irony is not lost on me. Himalayan treks are my prescription.",
        "city": "Coimbatore", "region": "Tamil Nadu", "country_code": "IN",
        "approx_lat": 11.00, "approx_lon": 76.97,
        "languages": ["Tamil", "English", "Telugu"],
        "travel_intentions": ["activity_partner", "travel_companion"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["hiking", "local_culture", "food_walks"],
        "trip_destination_slugs": ["kochi", "rishikesh"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 54, "gender": "male",
        "first_name": "Siddharth", "last_name": "Bose",
        "date_of_birth": "2001-12-08",
        "bio": "Computer science student building open-source mapping tools. I map places while backpacking.",
        "city": "Kolkata", "region": "West Bengal", "country_code": "IN",
        "approx_lat": 22.58, "approx_lon": 88.37,
        "languages": ["Bengali", "English", "Hindi"],
        "travel_intentions": ["travel_companion", "friends_social"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["everyone"],
        "discovery_preferences": ["everyone"],
        "interest_codes": ["photography", "local_culture", "art_design"],
        "trip_destination_slugs": ["kolkata", "singapore"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 55, "gender": "male",
        "first_name": "Omar", "last_name": "Sheikh",
        "date_of_birth": "1994-06-15",
        "bio": "Kashmiri craftsman and cultural ambassador. I sell Pashmina and sell stories about the Vale of Kashmir.",
        "city": "Srinagar", "region": "Jammu & Kashmir", "country_code": "IN",
        "approx_lat": 34.08, "approx_lon": 74.80,
        "languages": ["Kashmiri", "Urdu", "Hindi", "English"],
        "travel_intentions": ["local_guide", "friends_social"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["heritage", "local_culture", "art_design"],
        "trip_destination_slugs": ["kashmir", "new-delhi"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 56, "gender": "male",
        "first_name": "Ravi", "last_name": "Shankar",
        "date_of_birth": "1990-08-28",
        "bio": "Tabla player on a world music circuit. I've played in 22 countries, from Vienna to Buenos Aires.",
        "city": "Varanasi", "region": "Uttar Pradesh", "country_code": "IN",
        "approx_lat": 25.31, "approx_lon": 83.00,
        "languages": ["Hindi", "English", "Bhojpuri"],
        "travel_intentions": ["activity_partner", "friends_social"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women", "everyone"],
        "interest_codes": ["live_music", "heritage", "art_design"],
        "trip_destination_slugs": ["varanasi", "london"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 57, "gender": "male",
        "first_name": "Dhruv", "last_name": "Sharma",
        "date_of_birth": "1997-11-20",
        "bio": "Astronomer and dark-sky hunter. I plan trips around new-moon nights and remote star-gazing spots.",
        "city": "Jaipur", "region": "Rajasthan", "country_code": "IN",
        "approx_lat": 26.90, "approx_lon": 75.77,
        "languages": ["Hindi", "English", "Rajasthani"],
        "travel_intentions": ["activity_partner", "travel_companion"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["hiking", "photography", "local_culture"],
        "trip_destination_slugs": ["manali", "rishikesh"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 58, "gender": "male",
        "first_name": "Vivek", "last_name": "Iyer",
        "date_of_birth": "1988-01-31",
        "bio": "Architect and urban planner obsessed with public spaces. Parks, plazas, and bazaars tell a city's soul.",
        "city": "Mumbai", "region": "Maharashtra", "country_code": "IN",
        "approx_lat": 19.08, "approx_lon": 72.88,
        "languages": ["Tamil", "Hindi", "English"],
        "travel_intentions": ["activity_partner", "friends_social"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["art_design", "heritage", "local_culture"],
        "trip_destination_slugs": ["paris", "tokyo"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 59, "gender": "male",
        "first_name": "Ajay", "last_name": "Dubey",
        "date_of_birth": "2000-04-17",
        "bio": "Competitive swimmer and water sports enthusiast. Wherever there's water, I'm happy. Scuba next summer.",
        "city": "Bhopal", "region": "Madhya Pradesh", "country_code": "IN",
        "approx_lat": 23.25, "approx_lon": 77.40,
        "languages": ["Hindi", "English"],
        "travel_intentions": ["activity_partner", "travel_companion"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["beaches", "hiking", "photography"],
        "trip_destination_slugs": ["goa", "bali"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 60, "gender": "male",
        "first_name": "Ramesh", "last_name": "Nair",
        "date_of_birth": "1985-09-05",
        "bio": "Retired IPS officer now writing crime fiction. Every city I visit becomes a chapter in my next novel.",
        "city": "Kochi", "region": "Kerala", "country_code": "IN",
        "approx_lat": 9.94, "approx_lon": 76.27,
        "languages": ["Malayalam", "Hindi", "English"],
        "travel_intentions": ["friends_social", "travel_companion"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["heritage", "local_culture", "food_walks"],
        "trip_destination_slugs": ["kochi", "london"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 61, "gender": "male",
        "first_name": "Deepak", "last_name": "Rawat",
        "date_of_birth": "1995-12-14",
        "bio": "High-altitude rescue volunteer and paragliding instructor. The sky is not a limit — it's a playground.",
        "city": "Manali", "region": "Himachal Pradesh", "country_code": "IN",
        "approx_lat": 32.24, "approx_lon": 77.19,
        "languages": ["Hindi", "Kullu", "English"],
        "travel_intentions": ["activity_partner", "local_guide"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women", "everyone"],
        "interest_codes": ["hiking", "photography", "local_culture"],
        "trip_destination_slugs": ["manali", "kashmir"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 62, "gender": "male",
        "first_name": "Mohit", "last_name": "Sehgal",
        "date_of_birth": "1998-03-09",
        "bio": "Graphic novelist and street culture researcher. Comic panels inspired by Holi, Diwali, and neon bazaars.",
        "city": "New Delhi", "region": "Delhi", "country_code": "IN",
        "approx_lat": 28.62, "approx_lon": 77.21,
        "languages": ["Hindi", "English", "Punjabi"],
        "travel_intentions": ["activity_partner", "friends_social"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["everyone"],
        "discovery_preferences": ["everyone"],
        "interest_codes": ["art_design", "local_culture", "photography"],
        "trip_destination_slugs": ["jaipur", "tokyo"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 63, "gender": "male",
        "first_name": "Suraj", "last_name": "Patil",
        "date_of_birth": "1991-10-20",
        "bio": "Marathon runner training for six world majors. I run through every city I visit. 42 km = best city tour.",
        "city": "Pune", "region": "Maharashtra", "country_code": "IN",
        "approx_lat": 18.52, "approx_lon": 73.87,
        "languages": ["Marathi", "Hindi", "English"],
        "travel_intentions": ["activity_partner", "travel_companion"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["hiking", "local_culture", "food_walks"],
        "trip_destination_slugs": ["mumbai", "london"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 64, "gender": "male",
        "first_name": "Neeraj", "last_name": "Mishra",
        "date_of_birth": "2003-08-06",
        "bio": "First-year engineering student with a travel addiction funded by freelance coding. 5 states in 6 months.",
        "city": "Kanpur", "region": "Uttar Pradesh", "country_code": "IN",
        "approx_lat": 26.47, "approx_lon": 80.33,
        "languages": ["Hindi", "English"],
        "travel_intentions": ["travel_companion", "friends_social"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women", "everyone"],
        "interest_codes": ["photography", "local_culture", "food_walks"],
        "trip_destination_slugs": ["varanasi", "jaipur"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 65, "gender": "male",
        "first_name": "Hari", "last_name": "Menon",
        "date_of_birth": "1989-06-24",
        "bio": "Backwater boat captain turned eco-tour operator. I show tourists the Kerala that guidebooks miss.",
        "city": "Alleppey", "region": "Kerala", "country_code": "IN",
        "approx_lat": 9.49, "approx_lon": 76.33,
        "languages": ["Malayalam", "English", "Tamil"],
        "travel_intentions": ["local_guide", "travel_companion"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["local_culture", "beaches", "food_walks"],
        "trip_destination_slugs": ["kochi", "goa"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 66, "gender": "male",
        "first_name": "Sandeep", "last_name": "Pandya",
        "date_of_birth": "1992-01-13",
        "bio": "Botanist who photographs rare Himalayan flora. Plant-hunting is my treasure hunt.",
        "city": "Shimla", "region": "Himachal Pradesh", "country_code": "IN",
        "approx_lat": 31.10, "approx_lon": 77.18,
        "languages": ["Hindi", "English", "Pahari"],
        "travel_intentions": ["activity_partner", "travel_companion"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["hiking", "photography", "local_culture"],
        "trip_destination_slugs": ["manali", "rishikesh"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 67, "gender": "male",
        "first_name": "Alok", "last_name": "Chandra",
        "date_of_birth": "1997-05-01",
        "bio": "Social entrepreneur building rural homestays. I believe authentic hospitality is the best development model.",
        "city": "Ranchi", "region": "Jharkhand", "country_code": "IN",
        "approx_lat": 23.35, "approx_lon": 85.33,
        "languages": ["Hindi", "Odia", "English"],
        "travel_intentions": ["local_guide", "activity_partner"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["local_culture", "heritage", "food_walks"],
        "trip_destination_slugs": ["kolkata", "varanasi"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 68, "gender": "male",
        "first_name": "Pratik", "last_name": "Shah",
        "date_of_birth": "1999-11-11",
        "bio": "Diamond trader's son who prefers street markets. I find beauty in unpolished places.",
        "city": "Surat", "region": "Gujarat", "country_code": "IN",
        "approx_lat": 21.17, "approx_lon": 72.84,
        "languages": ["Gujarati", "Hindi", "English"],
        "travel_intentions": ["friends_social", "travel_companion"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["food_walks", "local_culture", "art_design"],
        "trip_destination_slugs": ["dubai", "singapore"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 69, "gender": "male",
        "first_name": "Abhijit", "last_name": "Das",
        "date_of_birth": "1990-04-03",
        "bio": "Jazz guitarist and sound engineer. I record ambient city sounds and layer them into jazz compositions.",
        "city": "Kolkata", "region": "West Bengal", "country_code": "IN",
        "approx_lat": 22.56, "approx_lon": 88.35,
        "languages": ["Bengali", "English", "Hindi"],
        "travel_intentions": ["activity_partner", "friends_social"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["live_music", "art_design", "local_culture"],
        "trip_destination_slugs": ["kolkata", "paris"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 70, "gender": "male",
        "first_name": "Shiv", "last_name": "Tomar",
        "date_of_birth": "1996-07-14",
        "bio": "Ex-army captain and motivational speaker. I organise veteran treks to the Himalayas. Purpose over comfort.",
        "city": "Dehradun", "region": "Uttarakhand", "country_code": "IN",
        "approx_lat": 30.31, "approx_lon": 78.02,
        "languages": ["Hindi", "English", "Garhwali"],
        "travel_intentions": ["activity_partner", "travel_companion"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["hiking", "local_culture", "photography"],
        "trip_destination_slugs": ["rishikesh", "kashmir"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 71, "gender": "male",
        "first_name": "Vinay", "last_name": "Choudhury",
        "date_of_birth": "1993-02-19",
        "bio": "Handicraft exporter connecting Indian artisans with global buyers. Jaipur block-print is my passion project.",
        "city": "Jaipur", "region": "Rajasthan", "country_code": "IN",
        "approx_lat": 26.91, "approx_lon": 75.79,
        "languages": ["Hindi", "English", "Rajasthani"],
        "travel_intentions": ["local_guide", "travel_companion"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women", "everyone"],
        "interest_codes": ["heritage", "art_design", "local_culture"],
        "trip_destination_slugs": ["jaipur", "udaipur"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 72, "gender": "male",
        "first_name": "Pranav", "last_name": "Kulkarni",
        "date_of_birth": "2002-10-10",
        "bio": "Physics undergrad obsessed with quantum mechanics and mountain fog. Science + nature = my everything.",
        "city": "Pune", "region": "Maharashtra", "country_code": "IN",
        "approx_lat": 18.53, "approx_lon": 73.88,
        "languages": ["Marathi", "Hindi", "English"],
        "travel_intentions": ["activity_partner", "friends_social"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["hiking", "photography", "local_culture"],
        "trip_destination_slugs": ["manali", "goa"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 73, "gender": "male",
        "first_name": "Rakesh", "last_name": "Bairwa",
        "date_of_birth": "1988-06-06",
        "bio": "Tribal arts researcher documenting indigenous craft traditions across Rajasthan and Madhya Pradesh.",
        "city": "Jodhpur", "region": "Rajasthan", "country_code": "IN",
        "approx_lat": 26.29, "approx_lon": 73.03,
        "languages": ["Marwari", "Hindi", "English"],
        "travel_intentions": ["activity_partner", "local_guide"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["heritage", "art_design", "local_culture"],
        "trip_destination_slugs": ["jaipur", "udaipur"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 74, "gender": "male",
        "first_name": "Manas", "last_name": "Deka",
        "date_of_birth": "1995-03-22",
        "bio": "Ornithologist from Assam. Counting birds is meditation. I've tracked species from the Sundarbans to Bhutan.",
        "city": "Guwahati", "region": "Assam", "country_code": "IN",
        "approx_lat": 26.14, "approx_lon": 91.74,
        "languages": ["Assamese", "Hindi", "English"],
        "travel_intentions": ["activity_partner", "travel_companion"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["hiking", "photography", "local_culture"],
        "trip_destination_slugs": ["kolkata", "kashmir"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 75, "gender": "male",
        "first_name": "Yash", "last_name": "Jain",
        "date_of_birth": "1999-09-09",
        "bio": "Tech consultant who runs a travel newsletter with 50k subscribers. I tell you the stories your travel agent won't.",
        "city": "Hyderabad", "region": "Telangana", "country_code": "IN",
        "approx_lat": 17.39, "approx_lon": 78.49,
        "languages": ["Telugu", "Hindi", "English"],
        "travel_intentions": ["travel_companion", "friends_social"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["food_walks", "local_culture", "photography"],
        "trip_destination_slugs": ["hyderabad", "singapore"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 76, "gender": "male",
        "first_name": "Farhan", "last_name": "Ansari",
        "date_of_birth": "1994-12-31",
        "bio": "Textile artist and backpacker. I weave fabric stories from every culture I visit. Kutch to Morocco.",
        "city": "Hyderabad", "region": "Telangana", "country_code": "IN",
        "approx_lat": 17.38, "approx_lon": 78.48,
        "languages": ["Urdu", "Telugu", "Hindi", "English"],
        "travel_intentions": ["activity_partner", "local_guide"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["art_design", "local_culture", "heritage"],
        "trip_destination_slugs": ["hyderabad", "jaipur"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 77, "gender": "male",
        "first_name": "Varun", "last_name": "Balachandran",
        "date_of_birth": "2000-08-18",
        "bio": "Business student who backpacked Europe on ₹50k. Budget travel is a skillset — I teach it online.",
        "city": "Bengaluru", "region": "Karnataka", "country_code": "IN",
        "approx_lat": 12.96, "approx_lon": 77.60,
        "languages": ["Kannada", "Tamil", "English"],
        "travel_intentions": ["travel_companion", "friends_social"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women", "everyone"],
        "interest_codes": ["local_culture", "food_walks", "photography"],
        "trip_destination_slugs": ["paris", "london"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 78, "gender": "male",
        "first_name": "Sanjay", "last_name": "Rathore",
        "date_of_birth": "1986-04-19",
        "bio": "Palace hotel heritage manager from Udaipur. I restore forgotten traditions one haveli at a time.",
        "city": "Udaipur", "region": "Rajasthan", "country_code": "IN",
        "approx_lat": 24.58, "approx_lon": 73.71,
        "languages": ["Hindi", "Rajasthani", "English"],
        "travel_intentions": ["local_guide", "travel_companion"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["heritage", "art_design", "local_culture"],
        "trip_destination_slugs": ["udaipur", "jaipur"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 79, "gender": "male",
        "first_name": "Hemant", "last_name": "Bisht",
        "date_of_birth": "1997-02-11",
        "bio": "Mountain rescue team volunteer and nature photographer. The Himalayas are my studio, classroom, and home.",
        "city": "Nainital", "region": "Uttarakhand", "country_code": "IN",
        "approx_lat": 29.38, "approx_lon": 79.46,
        "languages": ["Hindi", "Kumaoni", "English"],
        "travel_intentions": ["activity_partner", "travel_companion"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["hiking", "photography", "local_culture"],
        "trip_destination_slugs": ["rishikesh", "manali"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 80, "gender": "male",
        "first_name": "Girish", "last_name": "Swamy",
        "date_of_birth": "1993-07-07",
        "bio": "Startup CTO taking a one-year world tour. I work from wherever my laptop has internet and the view is epic.",
        "city": "Bengaluru", "region": "Karnataka", "country_code": "IN",
        "approx_lat": 12.97, "approx_lon": 77.59,
        "languages": ["Kannada", "English", "Hindi"],
        "travel_intentions": ["travel_companion", "friends_social"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["local_culture", "food_walks", "photography"],
        "trip_destination_slugs": ["bali", "tokyo"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 81, "gender": "male",
        "first_name": "Piyush", "last_name": "Tiwari",
        "date_of_birth": "1991-03-15",
        "bio": "Lawyer turned travel photographer. I left litigation for landscapes. No regrets since 2019.",
        "city": "Allahabad", "region": "Uttar Pradesh", "country_code": "IN",
        "approx_lat": 25.43, "approx_lon": 81.84,
        "languages": ["Hindi", "English", "Sanskrit"],
        "travel_intentions": ["activity_partner", "travel_companion"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["photography", "heritage", "local_culture"],
        "trip_destination_slugs": ["varanasi", "jaipur"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 82, "gender": "male",
        "first_name": "Chetan", "last_name": "Gaikwad",
        "date_of_birth": "1998-10-02",
        "bio": "Marathwada farmer's son chasing the world. I travel to understand what home means elsewhere.",
        "city": "Aurangabad", "region": "Maharashtra", "country_code": "IN",
        "approx_lat": 19.88, "approx_lon": 75.34,
        "languages": ["Marathi", "Hindi", "English"],
        "travel_intentions": ["travel_companion", "friends_social"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["heritage", "local_culture", "food_walks"],
        "trip_destination_slugs": ["mumbai", "goa"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 83, "gender": "male",
        "first_name": "Rahul", "last_name": "Venkatesh",
        "date_of_birth": "1994-05-25",
        "bio": "Aerospace engineer with a telescope addiction. I travel to dark sky reserves. Stars explain everything.",
        "city": "Chennai", "region": "Tamil Nadu", "country_code": "IN",
        "approx_lat": 13.08, "approx_lon": 80.27,
        "languages": ["Tamil", "English", "Hindi"],
        "travel_intentions": ["activity_partner", "travel_companion"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["photography", "hiking", "local_culture"],
        "trip_destination_slugs": ["manali", "kashmir"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 84, "gender": "male",
        "first_name": "Kunal", "last_name": "Malviya",
        "date_of_birth": "2001-06-30",
        "bio": "Animation student creating travel-inspired short films. I storyboard the world one city at a time.",
        "city": "Indore", "region": "Madhya Pradesh", "country_code": "IN",
        "approx_lat": 22.72, "approx_lon": 75.86,
        "languages": ["Hindi", "English", "Malwi"],
        "travel_intentions": ["activity_partner", "friends_social"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["everyone"],
        "discovery_preferences": ["everyone"],
        "interest_codes": ["art_design", "live_music", "photography"],
        "trip_destination_slugs": ["jaipur", "tokyo"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 85, "gender": "male",
        "first_name": "Naresh", "last_name": "Gowda",
        "date_of_birth": "1987-11-08",
        "bio": "Cardamom planter and trek leader in Coorg. I lead spice-trail treks and cook plantation meals.",
        "city": "Madikeri", "region": "Karnataka", "country_code": "IN",
        "approx_lat": 12.42, "approx_lon": 75.74,
        "languages": ["Kodava", "Kannada", "English"],
        "travel_intentions": ["local_guide", "activity_partner"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["food_walks", "hiking", "local_culture"],
        "trip_destination_slugs": ["kochi", "goa"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 86, "gender": "male",
        "first_name": "Abhishek", "last_name": "Soni",
        "date_of_birth": "1996-09-09",
        "bio": "Mechanical engineer and vintage motorcycle restorer. I ride bikes I build. Rajasthan royal roads await.",
        "city": "Jodhpur", "region": "Rajasthan", "country_code": "IN",
        "approx_lat": 26.29, "approx_lon": 73.03,
        "languages": ["Hindi", "Marwari", "English"],
        "travel_intentions": ["activity_partner", "travel_companion"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women", "everyone"],
        "interest_codes": ["heritage", "local_culture", "photography"],
        "trip_destination_slugs": ["jaipur", "udaipur"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 87, "gender": "male",
        "first_name": "Sunny", "last_name": "Walia",
        "date_of_birth": "1999-01-17",
        "bio": "DJ and electronic music producer. I play at beach parties worldwide. Goa trance is my religion.",
        "city": "Chandigarh", "region": "Punjab", "country_code": "IN",
        "approx_lat": 30.74, "approx_lon": 76.79,
        "languages": ["Punjabi", "Hindi", "English"],
        "travel_intentions": ["friends_social", "activity_partner"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["live_music", "beaches", "local_culture"],
        "trip_destination_slugs": ["goa", "bali"],
        "companion_preference": "travelling_with_group",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 88, "gender": "male",
        "first_name": "Joel", "last_name": "Fernandez",
        "date_of_birth": "1992-04-28",
        "bio": "Goan-born marine biologist and freediver. My office is the ocean. I study coral restoration by day.",
        "city": "Panaji", "region": "Goa", "country_code": "IN",
        "approx_lat": 15.50, "approx_lon": 73.84,
        "languages": ["Konkani", "English", "Portuguese", "Hindi"],
        "travel_intentions": ["activity_partner", "travel_companion"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["beaches", "photography", "local_culture"],
        "trip_destination_slugs": ["goa", "bali"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 89, "gender": "male",
        "first_name": "Tariq", "last_name": "Hussain",
        "date_of_birth": "1995-08-15",
        "bio": "Kashmiri calligrapher and heritage guide. Every inscription on a mosque wall tells a forgotten dynasty's story.",
        "city": "Srinagar", "region": "Jammu & Kashmir", "country_code": "IN",
        "approx_lat": 34.07, "approx_lon": 74.79,
        "languages": ["Kashmiri", "Urdu", "Hindi", "English"],
        "travel_intentions": ["local_guide", "friends_social"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["heritage", "art_design", "local_culture"],
        "trip_destination_slugs": ["kashmir", "new-delhi"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 90, "gender": "male",
        "first_name": "Arun", "last_name": "Subramanian",
        "date_of_birth": "1990-12-12",
        "bio": "Neuroscientist turned travel therapist. I run 'mindful travel' retreats for burned-out professionals.",
        "city": "Chennai", "region": "Tamil Nadu", "country_code": "IN",
        "approx_lat": 13.09, "approx_lon": 80.28,
        "languages": ["Tamil", "English", "French"],
        "travel_intentions": ["travel_companion", "activity_partner"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["local_culture", "heritage", "food_walks"],
        "trip_destination_slugs": ["bali", "rishikesh"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 91, "gender": "male",
        "first_name": "Bipin", "last_name": "Thapa",
        "date_of_birth": "1993-10-04",
        "bio": "Ex-Gurkha officer and extreme trekker. I've completed Annapurna Circuit 4 times. Rest is overrated.",
        "city": "Gangtok", "region": "Sikkim", "country_code": "IN",
        "approx_lat": 27.33, "approx_lon": 88.61,
        "languages": ["Nepali", "Hindi", "English"],
        "travel_intentions": ["activity_partner", "travel_companion"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["hiking", "photography", "local_culture"],
        "trip_destination_slugs": ["kashmir", "manali"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 92, "gender": "male",
        "first_name": "Gautam", "last_name": "Lakra",
        "date_of_birth": "1997-07-27",
        "bio": "Social media creator and van-lifer. I've driven across 11 Indian states in a converted camper van.",
        "city": "Bhopal", "region": "Madhya Pradesh", "country_code": "IN",
        "approx_lat": 23.26, "approx_lon": 77.41,
        "languages": ["Hindi", "English", "Gondi"],
        "travel_intentions": ["travel_companion", "friends_social"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women", "everyone"],
        "interest_codes": ["local_culture", "photography", "food_walks"],
        "trip_destination_slugs": ["goa", "mumbai"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 93, "gender": "male",
        "first_name": "Mohan", "last_name": "Das",
        "date_of_birth": "1985-02-05",
        "bio": "NGO founder working in tribal education. I travel to remote villages, not resorts. Real India is rural India.",
        "city": "Bhubaneswar", "region": "Odisha", "country_code": "IN",
        "approx_lat": 20.30, "approx_lon": 85.84,
        "languages": ["Odia", "Hindi", "English"],
        "travel_intentions": ["friends_social", "local_guide"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["local_culture", "heritage", "art_design"],
        "trip_destination_slugs": ["kolkata", "varanasi"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 94, "gender": "male",
        "first_name": "Diljit", "last_name": "Sodhi",
        "date_of_birth": "1998-05-05",
        "bio": "Bhangra dancer performing internationally. I represent Punjab in every city I dance in.",
        "city": "Amritsar", "region": "Punjab", "country_code": "IN",
        "approx_lat": 31.63, "approx_lon": 74.87,
        "languages": ["Punjabi", "Hindi", "English"],
        "travel_intentions": ["activity_partner", "friends_social"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["live_music", "local_culture", "food_walks"],
        "trip_destination_slugs": ["new-delhi", "dubai"],
        "companion_preference": "travelling_with_group",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 95, "gender": "male",
        "first_name": "Saurabh", "last_name": "Tambe",
        "date_of_birth": "1991-07-07",
        "bio": "Geographer and map illustrator. I hand-draw cities from memory after each trip. Cartography is storytelling.",
        "city": "Nagpur", "region": "Maharashtra", "country_code": "IN",
        "approx_lat": 21.14, "approx_lon": 79.08,
        "languages": ["Marathi", "Hindi", "English"],
        "travel_intentions": ["activity_partner", "travel_companion"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["art_design", "heritage", "photography"],
        "trip_destination_slugs": ["jaipur", "kolkata"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 96, "gender": "male",
        "first_name": "Sudhir", "last_name": "Garg",
        "date_of_birth": "1989-09-09",
        "bio": "Retired school teacher who started solo travelling at 35. Every trip proves you can begin again at any age.",
        "city": "Agra", "region": "Uttar Pradesh", "country_code": "IN",
        "approx_lat": 27.18, "approx_lon": 78.01,
        "languages": ["Hindi", "English", "Braj"],
        "travel_intentions": ["travel_companion", "friends_social"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["heritage", "local_culture", "food_walks"],
        "trip_destination_slugs": ["new-delhi", "varanasi"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 97, "gender": "male",
        "first_name": "Kartik", "last_name": "Naik",
        "date_of_birth": "2002-11-28",
        "bio": "Aspiring journalist documenting India's disappearing festivals. I race against time and modernity.",
        "city": "Panaji", "region": "Goa", "country_code": "IN",
        "approx_lat": 15.49, "approx_lon": 73.83,
        "languages": ["Konkani", "Marathi", "English", "Hindi"],
        "travel_intentions": ["activity_partner", "friends_social"],
        "dating_intentions": ["casual_dating"],
        "dating_preferences": ["everyone"],
        "discovery_preferences": ["everyone"],
        "interest_codes": ["heritage", "local_culture", "photography"],
        "trip_destination_slugs": ["goa", "kolkata"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 98, "gender": "male",
        "first_name": "Lakshmikant", "last_name": "Rao",
        "date_of_birth": "1994-04-20",
        "bio": "Classical Bharatanatyam teacher and cultural exchange coordinator. Dance = diplomacy.",
        "city": "Hyderabad", "region": "Telangana", "country_code": "IN",
        "approx_lat": 17.38, "approx_lon": 78.48,
        "languages": ["Telugu", "Hindi", "English", "Tamil"],
        "travel_intentions": ["activity_partner", "friends_social"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["art_design", "live_music", "heritage"],
        "trip_destination_slugs": ["hyderabad", "london"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
    {
        "seed_index": 99, "gender": "male",
        "first_name": "Ramakrishna", "last_name": "Pillai",
        "date_of_birth": "1986-03-03",
        "bio": "Ayurveda physician and slow traveller. I write prescriptions for rest, nature, and good food. Travel is medicine.",
        "city": "Thrissur", "region": "Kerala", "country_code": "IN",
        "approx_lat": 10.52, "approx_lon": 76.21,
        "languages": ["Malayalam", "Sanskrit", "English", "Hindi"],
        "travel_intentions": ["travel_companion", "activity_partner"],
        "dating_intentions": ["serious_relationship"],
        "dating_preferences": ["women"],
        "discovery_preferences": ["women"],
        "interest_codes": ["local_culture", "heritage", "food_walks"],
        "trip_destination_slugs": ["kochi", "rishikesh"],
        "companion_preference": "open_to_companion",
        "trip_visibility": "discoverable",
    },
]

# ---------------------------------------------------------------------------
# Combined list in seed_index order
# ---------------------------------------------------------------------------
ALL_PROFILES: list[PersonSpec] = FEMALE_PROFILES + MALE_PROFILES


def validate_counts() -> None:
    female = [p for p in ALL_PROFILES if p["gender"] == "female"]
    male = [p for p in ALL_PROFILES if p["gender"] == "male"]
    total = len(ALL_PROFILES)
    assert len(female) == 34, f"Expected 34 female profiles, got {len(female)}"
    assert len(male) == 65, f"Expected 65 male profiles, got {len(male)}"
    assert total == 99, f"Expected 99 total profiles, got {total}"
    indices = {p["seed_index"] for p in ALL_PROFILES}
    assert indices == set(range(1, 100)), "seed_index values must be 1..99 with no gaps"
